// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "NanoDictate",
    platforms: [
        .macOS(.v12),
    ],
    products: [
        .library(name: "NanoDictateCore", targets: ["NanoDictateCore"]),
        .executable(name: "NanoDictateAgent", targets: ["NanoDictateAgent"]),
        .executable(name: "nanodictate", targets: ["nanodictate"]),
    ],
    // Линтеры не живут в SPM-графе: свежие релизы SwiftLint требуют
    // tools-version 5.9, локальный тулчейн — 5.7; резолвинг зависимостей
    // падает. Линтеры работают как внешние бинари: pre-commit хук (.githooks)
    // и отдельные шаги CI.
    targets: [
        // ObjC-шлюз NSException AVFAudio: SPM 5.7 не допускает подмешивание
        // ObjC в Swift-таргеты, поэтому шлюз живёт отдельным clang-таргетом.
        .target(
            name: "AudioEngineGuard",
            publicHeadersPath: "include"
        ),
        // C header of the shared Rust engine (Sources/NanoDictateRustFFI).
        // The header is generated by cbindgen from rust/nanodictate-core
        // (scripts/build-rust-core.sh); the static library itself is linked
        // by absolute archive path (-Xlinker .../libnanodictate_core.a) by
        // the same script (see docs/architecture-rust-engine.md).
        .target(
            name: "NanoDictateRustFFI",
            publicHeadersPath: "include"
        ),
        // Idiomatic Swift surface over the Rust C ABI. No behavior lives
        // here; deterministic product logic lives in Rust.
        .target(
            name: "NanoDictateRustBridge",
            dependencies: ["NanoDictateRustFFI"]
        ),
        .target(
            name: "NanoDictateCore",
            dependencies: ["AudioEngineGuard", "NanoDictateRustBridge"]
        ),
        .executableTarget(
            name: "NanoDictateAgent",
            dependencies: ["NanoDictateCore"]
        ),
        .executableTarget(
            name: "nanodictate",
            dependencies: ["NanoDictateCore"]
        ),
        // Компактный раннер тестов: на этой машине нет Xcode / XCTest.framework,
        // поэтому `swift test` физически не работает ("XCTest not available").
        // Исполняемый таргет прогоняет те же проверки и завершается с ненулевым
        // кодом при первом упавшем тесте: build the Rust archive first
        // (`scripts/build-rust-core.sh`), then
        // `swift run -Xlinker rust/target/release/libnanodictate_core.a NanoDictateCoreTests`.
        .executableTarget(
            name: "NanoDictateCoreTests",
            dependencies: ["NanoDictateCore", "AudioEngineGuard", "NanoDictateRustBridge"],
            path: "Tests/NanoDictateCoreTests"
        ),
    ]
)
