#ifndef nanodictate_core
#define nanodictate_core

/* Generated with cbindgen:0.27.0 */

/* Warning: this file is generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version. Bumped on any incompatible change to this module.
 */
#define ND_ABI_VERSION 1

/**
 * Dictation cycle state codes (see [`DictationState`]).
 */
#define ND_STATE_IDLE 0

#define ND_STATE_RECORDING 1

#define ND_STATE_TRANSCRIBING 2

/**
 * Session event codes (see [`SessionEvent`]).
 */
#define ND_EVENT_ENGINE_STARTED 0

#define ND_EVENT_FIRST_BUFFER 1

#define ND_EVENT_ENGINE_FAILED 2

#define ND_EVENT_CANCELLED 3

#define ND_EVENT_STOP_REQUESTED 4

#define ND_EVENT_TRANSCRIPTION_DONE 5

/**
 * Success.
 */
#define ND_OK 0

/**
 * A required pointer argument was null.
 */
#define ND_ERR_NULL 1

/**
 * Input bytes were not valid UTF-8 where UTF-8 was required.
 */
#define ND_ERR_UTF8 2

/**
 * An argument was out of range (negative length, bad rate, ...).
 */
#define ND_ERR_ARG 3

/**
 * The caller-provided output buffer is too small.
 */
#define ND_ERR_SMALL_BUFFER 4

/**
 * The input could not be decoded (malformed WAV/JSON, ...).
 */
#define ND_ERR_DECODE 5

/**
 * Internal error (allocation failure, poisoned lock, ...).
 */
#define ND_ERR_INTERNAL 6

/**
 * A Rust panic was caught at the ABI boundary.
 */
#define ND_ERR_PANIC 100

/**
 * Opaque silence auto-stop handle.
 */
typedef struct NdAutoStop NdAutoStop;

/**
 * Opaque mic-error cooldown handle.
 */
typedef struct NdCooldown NdCooldown;

/**
 * Opaque input-gain handle.
 */
typedef struct NdGain NdGain;

/**
 * Opaque enter-send latch handle.
 */
typedef struct NdLatch NdLatch;

/**
 * Opaque dictation session handle.
 */
typedef struct NdSession NdSession;

/**
 * Opaque adaptive VAD handle.
 */
typedef struct NdVad NdVad;

/**
 * Byte buffer owned by the caller. Release with [`nd_bytes_free`].
 */
typedef struct NdByteBuffer {
  uint8_t *data;
  size_t len;
  size_t cap;
} NdByteBuffer;





/**
 * Returns the ABI version ([`ND_ABI_VERSION`]).
 */
uint32_t nd_abi_version(void);

/**
 * Returns the thread-local last-error diagnostic as NUL-terminated UTF-8.
 * Valid until the next fallible call on the same thread. Never NULL.
 */
const char *nd_last_error_text(void);

/**
 * Releases a string returned by this ABI. NULL is accepted and ignored.
 */
void nd_string_free(char *text);

/**
 * Releases an [`NdByteBuffer`] returned by this ABI.
 */
void nd_bytes_free(struct NdByteBuffer buffer);

/**
 * Linear amplitude (0..1) to dBFS. Never fails.
 */
float nd_dbfs(float linear);

/**
 * RMS over Int16 samples (0..1). Returns -1.0 and records an error when
 * `samples` is NULL with a nonzero count.
 */
float nd_rms_i16(const int16_t *samples, size_t count);

/**
 * RMS over Float32 samples (0..1). Same error convention as [`nd_rms_i16`].
 */
float nd_rms_f32(const float *samples, size_t count);

/**
 * Bounded soft-limiter for one sample. Never fails.
 */
float nd_soft_limit(float x);

/**
 * Encodes Int16 samples as 16-bit PCM WAV into `out`. Byte-identical to
 * the native encoder for the same inputs.
 */
int32_t nd_wav_encode(const int16_t *samples,
                      size_t count,
                      uint32_t sample_rate,
                      uint16_t channels,
                      struct NdByteBuffer *out);

/**
 * Reads WAV header metadata without copying samples. Only the window up
 * to the `data` chunk header must be present.
 */
int32_t nd_wav_decode_info(const uint8_t *data,
                           size_t len,
                           uint32_t *out_sample_rate,
                           uint16_t *out_channels,
                           size_t *out_sample_count);

/**
 * Full WAV header metadata without copying samples: sample rate,
 * channels, bits per sample, PCM payload offset/size, and sample count.
 * Only the window up to the `data` chunk header must be present. This is
 * the file-backed batch source contract (the streaming capture path never
 * parses headers). Returns `ND_OK` or a positive `ND_ERR_*` code.
 */
int32_t nd_wav_header_full(const uint8_t *data,
                           size_t len,
                           uint32_t *out_sample_rate,
                           uint16_t *out_channels,
                           uint16_t *out_bits_per_sample,
                           size_t *out_data_offset,
                           size_t *out_data_size,
                           size_t *out_sample_count);

/**
 * Decodes WAV samples into the caller-provided buffer. Query the required
 * capacity with [`nd_wav_decode_info`]; `ND_ERR_SMALL_BUFFER` is returned
 * when `capacity` is too small.
 */
int32_t nd_wav_decode_samples(const uint8_t *data,
                              size_t len,
                              int16_t *out_samples,
                              size_t capacity,
                              size_t *out_written);

/**
 * Word-level diff as JSON: `{"change":false}` when texts match word-wise,
 * else `{"change":true,"span_old":...,"span_new":...,"span_start_old":N,
 * "span_start_new":N}`. NULL is returned only on error.
 */
char *nd_word_diff(const char *old_ptr, size_t old_len, const char *new_ptr, size_t new_len);

/**
 * Text tail after the first `word_count` words (post-processing overlap
 * helper, mirrors `WordDiff.tailAfterWords`). Leading whitespace stays on
 * the tail; the native insertion layer trims it. NULL only on invalid
 * UTF-8, null pointers, or panic.
 */
char *nd_word_tail_after_words(const char *text_ptr, size_t text_len, size_t word_count);

/**
 * Joins `count` chunk texts (`texts`/`lens` arrays) with boundary-overlap
 * dedup. NULL is returned only on error.
 */
char *nd_text_join(const char *const *texts, const size_t *lens, size_t count);

/**
 * Resolves the model profile for an (adapter id, model) pair as JSON.
 * Never fails on unknown ids (conservative fallback); NULL only on
 * invalid UTF-8, null pointers, or panic.
 */
char *nd_stt_resolve(const char *adapter_ptr,
                     size_t adapter_len,
                     const char *model_ptr,
                     size_t model_len);

/**
 * Default endpoint for an adapter id (empty for manual endpoints that
 * require an explicit base URL). Mirrors the portable configuration
 * default so macOS and Windows resolve the same value. NULL only on
 * invalid UTF-8, null pointers, or panic.
 */
char *nd_stt_default_base_url(const char *adapter_ptr, size_t adapter_len);

/**
 * Default model for an adapter id (empty when the adapter has none and
 * the model must come from configuration). Mirrors the portable
 * configuration default. NULL only on invalid UTF-8, null pointers, or
 * panic.
 */
char *nd_stt_default_model(const char *adapter_ptr, size_t adapter_len);

/**
 * Parses an STT response body into `{"text":...,"words":[...]}` JSON.
 * `path` selects the transcript field (`NULL`/empty means flat `text`;
 * otherwise a dot-separated path such as `result.text`). NULL only on
 * parse errors, invalid UTF-8, or panic. Empty text is an empty result,
 * not an error.
 */
char *nd_transcript_parse(const char *body_ptr,
                          size_t body_len,
                          const char *path_ptr,
                          size_t path_len);

/**
 * Orders failover candidates as comma-separated ids. `failed` selects the
 * last-failed provider (empty means none). `auto_failover` nonzero moves
 * it to the end. NULL only on error.
 */
char *nd_failover_order(const char *ids_ptr,
                        size_t ids_len,
                        const char *failed_ptr,
                        size_t failed_len,
                        bool auto_failover);

/**
 * Number of candidates the caller may attempt. Never fails.
 */
size_t nd_failover_candidate_count(size_t order_len, bool auto_failover);

/**
 * Whether a failed attempt of `kind` (0 = transcribe error, else other)
 * may fall over to the next provider. Never fails.
 */
bool nd_should_failover(uint32_t kind);

/**
 * Exponential backoff delay in milliseconds. Never fails.
 */
uint64_t nd_backoff_delay_ms(uint32_t attempt, uint64_t base_ms, uint64_t cap_ms);

/**
 * Review-before-insert decision: 1 = insert, 0 = cancel. `has_line`
 * false means end of input (cancel). Negative values are errors.
 */
int32_t nd_review_decide(const char *line_ptr, size_t line_len, bool has_line);

/**
 * Retry-insertion drop guard: 1 = drop, 0 = keep. Negative values are errors.
 */
int32_t nd_should_drop_retry(uint32_t state, uint64_t processing_session, uint64_t session);

/**
 * Overlay hide rule: 1 = may hide, 0 = must stay. Negative values are errors.
 */
int32_t nd_overlay_should_hide(uint32_t state);

/**
 * Mic-request storm guard: 1 = a new request is allowed, 0 = blocked.
 * Negative values are errors.
 */
int32_t nd_mic_request_allowed(const double *stamps,
                               size_t count,
                               double now,
                               size_t max_timeouts,
                               double window_secs);

/**
 * Creates an adaptive VAD handle with default configuration. NULL only on
 * panic (allocation failure aborts the process).
 */
struct NdVad *nd_vad_new(void);

/**
 * Releases a VAD handle. NULL is accepted and ignored.
 */
void nd_vad_free(struct NdVad *handle);

/**
 * Feeds one buffer RMS with its duration. Returns 1 for speech, 0 for
 * silence, negative on error.
 */
int32_t nd_vad_feed(struct NdVad *handle, float rms, double duration);

/**
 * Realtime ingress: feeds one block of Float32 samples at `sample_rate`.
 * Computes the block RMS inline (no allocation) and updates the detector.
 * Returns 1 for speech, 0 for silence, negative on error. Never performs
 * I/O, locking, or network work.
 */
int32_t nd_vad_feed_samples(struct NdVad *handle,
                            const float *samples,
                            size_t count,
                            uint32_t sample_rate);

/**
 * Resets a VAD handle to the initial state. Returns `ND_OK` or a positive `ND_ERR_*` code.
 */
int32_t nd_vad_reset(struct NdVad *handle);

/**
 * Creates an input-gain handle with default configuration.
 */
struct NdGain *nd_gain_new(void);

/**
 * Releases an input-gain handle. NULL is accepted and ignored.
 */
void nd_gain_free(struct NdGain *handle);

/**
 * Applies gain in place; returns the amplified RMS, or a negative value
 * on error. `rms` is the pre-gain RMS of the block.
 */
float nd_gain_apply(struct NdGain *handle,
                    float *samples,
                    size_t count,
                    float rms,
                    uint32_t sample_rate);

/**
 * Creates an auto-stop handle with default configuration.
 */
struct NdAutoStop *nd_autostop_new(void);

/**
 * Releases an auto-stop handle. NULL is accepted and ignored.
 */
void nd_autostop_free(struct NdAutoStop *handle);

/**
 * Feeds one buffer. `is_speech`: 1 = speech, 0 = silence, negative =
 * no VAD hint (RMS thresholds apply). Returns 1 when all stop
 * conditions hold, 0 otherwise, negative on error.
 */
int32_t nd_autostop_feed(struct NdAutoStop *handle, float rms, double duration, int32_t is_speech);

/**
 * Creates a dictation session handle in the idle state.
 */
struct NdSession *nd_session_new(void);

/**
 * Releases a session handle. NULL is accepted and ignored.
 */
void nd_session_free(struct NdSession *handle);

/**
 * Starts a new session (bumps the generation, clears readiness) and
 * returns the new generation. Returns 0 on error (generations start at 1).
 */
uint64_t nd_session_start(struct NdSession *handle);

/**
 * Drives the session with an event for a generation. Stale generations
 * are rejected silently. Returns `ND_OK` or a positive `ND_ERR_*` code.
 */
int32_t nd_session_event(struct NdSession *handle, uint32_t event, uint64_t generation);

/**
 * Live capture-readiness flag. Returns 1 when ready, 0 otherwise,
 * negative on error.
 */
int32_t nd_session_is_capture_ready(struct NdSession *handle);

/**
 * Whether the recording-ready cue may be emitted now (at most once per
 * session, only after readiness). Returns 1 to emit, 0 to suppress,
 * negative on error.
 */
int32_t nd_session_should_emit_ready_cue(struct NdSession *handle);

/**
 * Current session state code. Returns `ND_STATE_*` or `u32::MAX` on error.
 */
uint32_t nd_session_state(struct NdSession *handle);

/**
 * Creates a mic-error cooldown handle with the given interval in seconds.
 */
struct NdCooldown *nd_cooldown_new(double interval_secs);

/**
 * Releases a cooldown handle. NULL is accepted and ignored.
 */
void nd_cooldown_free(struct NdCooldown *handle);

/**
 * Cooldown check: 1 = show allowed (records `now`), 0 = suppressed,
 * negative on error.
 */
int32_t nd_cooldown_allow(struct NdCooldown *handle, double now_secs);

/**
 * Creates an enter-send latch handle.
 */
struct NdLatch *nd_latch_new(void);

/**
 * Releases a latch handle. NULL is accepted and ignored.
 */
void nd_latch_free(struct NdLatch *handle);

/**
 * Arms the latch. Returns `ND_OK` or a positive `ND_ERR_*` code.
 */
int32_t nd_latch_arm(struct NdLatch *handle);

/**
 * One-shot take: 1 = post Enter, 0 = already consumed, negative on error.
 */
int32_t nd_latch_consume(struct NdLatch *handle);

/**
 * Disarms the latch. Returns `ND_OK` or a positive `ND_ERR_*` code.
 */
int32_t nd_latch_cancel(struct NdLatch *handle);

#endif  /* nanodictate_core */
