name: remove-review-ready-on-sync

on:
  pull_request:
    types: [synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  call:
    uses: kodmial/continuum/.github/workflows/remove-review-label.yml@6c285dcd47f13919bb1af3be694bcc92c9f42356
    secrets: inherit
    with:
      continuum_ref: 6c285dcd47f13919bb1af3be694bcc92c9f42356
