name: PR Agent (manual, Groq)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  call:
    uses: kodmial/continuum/.github/workflows/continuum-pr-agent.yml@v.0.0.2
    secrets: inherit
    with:
      continuum_ref: "v.0.0.2"
