name: remove-review-ready-on-sync

on:
  pull_request:
    types: [synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  call:
    uses: kodmial/continuum/.github/workflows/continuum-remove-review-label.yml@v.0.0.2
    secrets: inherit
    with:
      continuum_ref: "v.0.0.2"
