name: release-automation-merge

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  call:
    uses: kodmial/continuum/.github/workflows/release-automation-merge.yml@main
    secrets: inherit
